name             'networkmanager'
maintainer       'Oregon State University'
maintainer_email 'chef@osuosl.org'
license          'Apache-2.0'
chef_version     '>= 13'
issues_url       'https://github.com/osuosl-cookbooks/networkmanager/issues'
source_url       'https://github.com/osuosl-cookbooks/networkmanager'
description      'Installs/Configures networkmanager'
long_description 'Installs/Configures networkmanager'
version          '0.1.0'

supports         'centos', '~> 7.0'
